spring:
  application:
    name: 'Meetup'
  main:
    banner-mode: log
  banner:
    location: 'classpath:config/banner.txt'

management:
  influx:
    metrics:
      export:
        enabled: false

server:
  port: 8080
  servlet:
    context-path: /couchbase-meetup
